// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReferWell.Infrastructure.Data;

#nullable disable

namespace ReferWell.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260712075614_AddReferralSlaPause")]
    partial class AddReferralSlaPause
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ReferWell.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Email = "admin@referwell.com",
                            FullName = "John Doe",
                            Gender = "Male",
                            IsActive = true,
                            PasswordHash = "$2a$11$arWPA0e0Rr39IxILEk65neV.Nl1Mrpo9V7u4F6BkE.A/X2orLaEpS",
                            PhoneNumber = "+64 21 111 2222",
                            Title = "Mr."
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Email = "nurse@referwell.com",
                            FullName = "Sarah Jenkins",
                            Gender = "Female",
                            IsActive = true,
                            PasswordHash = "$2a$11$eO2F/KcbP7Rj1VH.E8q8P.wrSV.5EFsJhP3aeu7WlXXg.7bsmnzZK",
                            PhoneNumber = "+64 22 222 3333",
                            Title = "Mrs."
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Email = "gp1@referwell.com",
                            FullName = "James Wilson",
                            Gender = "Male",
                            IsActive = true,
                            PasswordHash = "$2a$11$uBK1YEZH/Dp3XgGKSD5SwukkEMJMO5soXjm.0ms.f2eZeGMkT4hJC",
                            PhoneNumber = "+64 27 333 4444",
                            Title = "Dr."
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Email = "gp2@referwell.com",
                            FullName = "Amelia Hart",
                            Gender = "Female",
                            IsActive = true,
                            PasswordHash = "$2a$11$QFsJKNAvB8isQ1suhdU8T.8z0fKVB4nA3Esj1G7hW6XPzFSYtTwpu",
                            PhoneNumber = "+64 29 444 5555",
                            Title = "Dr."
                        });
                });

            modelBuilder.Entity("ReferWell.Domain.Entities.ApplicationUserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("tblUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-2222-3333-4444-555555555551"),
                            Role = 1,
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("11111111-2222-3333-4444-555555555552"),
                            Role = 2,
                            UserId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("11111111-2222-3333-4444-555555555553"),
                            Role = 3,
                            UserId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("11111111-2222-3333-4444-555555555554"),
                            Role = 3,
                            UserId = new Guid("44444444-4444-4444-4444-444444444444")
                        });
                });

            modelBuilder.Entity("ReferWell.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FromStatus")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PerformedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReferralId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ToStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PerformedByUserId");

                    b.HasIndex("ReferralId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("ReferWell.Domain.Entities.MassCommCampaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BodyTemplate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FilterCriteria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubjectTemplate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("MassCommCampaigns");
                });

            modelBuilder.Entity("ReferWell.Domain.Entities.MassCommMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecipientEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecipientType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferralCaseNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ReferralId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RenderedBody")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RenderedSubject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.ToTable("MassCommMessages");
                });

            modelBuilder.Entity("ReferWell.Domain.Entities.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NhiNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tblPatient", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            CreatedAt = new DateTime(2026, 7, 12, 19, 56, 13, 533, DateTimeKind.Local).AddTicks(2460),
                            DateOfBirth = new DateTime(1955, 3, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            Email = "alice.martin@example.com",
                            Gender = "Female",
                            Name = "Alice Martin",
                            NhiNumber = "ABC1234",
                            PhoneNumber = "+64 21 555 0101"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666655555555"),
                            CreatedAt = new DateTime(2026, 7, 12, 19, 56, 13, 533, DateTimeKind.Local).AddTicks(2487),
                            DateOfBirth = new DateTime(1970, 7, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            Email = "bob.clarke@example.com",
                            Gender = "Male",
                            Name = "Bob Clarke",
                            NhiNumber = "DEF5678",
                            PhoneNumber = "+64 22 555 0102"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777755555555"),
                            CreatedAt = new DateTime(2026, 7, 12, 19, 56, 13, 533, DateTimeKind.Local).AddTicks(2491),
                            DateOfBirth = new DateTime(1940, 11, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            Email = "carol.ahmed@example.com",
                            Gender = "Female",
                            Name = "Carol Ahmed",
                            NhiNumber = "GHI9012",
                            PhoneNumber = "+64 27 555 0103"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888855555555"),
                            CreatedAt = new DateTime(2026, 7, 12, 19, 56, 13, 533, DateTimeKind.Local).AddTicks(2495),
                            DateOfBirth = new DateTime(1985, 2, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            Email = "david.johnson@example.com",
                            Gender = "Male",
                            Name = "David Johnson",
                            NhiNumber = "JKL3456",
                            PhoneNumber = "+64 29 555 0104"
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999955555555"),
                            CreatedAt = new DateTime(2026, 7, 12, 19, 56, 13, 533, DateTimeKind.Local).AddTicks(2498),
                            DateOfBirth = new DateTime(1932, 8, 30, 0, 0, 0, 0, DateTimeKind.Local),
                            Email = "eva.rodriguez@example.com",
                            Gender = "Female",
                            Name = "Eva Rodriguez",
                            NhiNumber = "MNO7890",
                            PhoneNumber = "+64 21 555 0105"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-5555-5555-5555-555555555555"),
                            CreatedAt = new DateTime(2026, 7, 12, 19, 56, 13, 533, DateTimeKind.Local).AddTicks(2503),
                            DateOfBirth = new DateTime(1960, 4, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            Email = "frank.lee@example.com",
                            Gender = "Male",
                            Name = "Frank Lee",
                            NhiNumber = "PQR1234",
                            PhoneNumber = "+64 22 555 0106"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-5555-5555-5555-555555555555"),
                            CreatedAt = new DateTime(2026, 7, 12, 19, 56, 13, 533, DateTimeKind.Local).AddTicks(2506),
                            DateOfBirth = new DateTime(1978, 12, 3, 0, 0, 0, 0, DateTimeKind.Local),
                            Email = "grace.kim@example.com",
                            Gender = "Female",
                            Name = "Grace Kim",
                            NhiNumber = "STU5678",
                            PhoneNumber = "+64 27 555 0107"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-5555-5555-5555-555555555555"),
                            CreatedAt = new DateTime(2026, 7, 12, 19, 56, 13, 533, DateTimeKind.Local).AddTicks(2513),
                            DateOfBirth = new DateTime(1945, 6, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Email = "henry.smith@example.com",
                            Gender = "Male",
                            Name = "Henry Smith",
                            NhiNumber = "VWX9012",
                            PhoneNumber = "+64 29 555 0108"
                        });
                });

            modelBuilder.Entity("ReferWell.Domain.Entities.Referral", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssignedToUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CaseNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("ClaimedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ClaimedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("PriorityScore")
                        .HasColumnType("float");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReferringGPId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<bool>("SlaBreach")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SlaDeadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("SlaPauseReason")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("SlaPaused")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SlaPausedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SpecialistType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Urgency")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("ClaimedByUserId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("PatientId");

                    b.ToTable("Referrals");

                    b.HasData(
                        new
                        {
                            Id = new Guid("62c3cd59-f32d-4961-9c23-9b2d126f8aa3"),
                            AssignedToUserId = new Guid("33333333-3333-3333-3333-333333333333"),
                            CaseNo = "Ref-000001",
                            CreatedAt = new DateTime(2024, 5, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedByUserId = new Guid("33333333-3333-3333-3333-333333333333"),
                            PatientId = new Guid("55555555-5555-5555-5555-555555555555"),
                            PriorityScore = 75.5,
                            Reason = "Chest pain",
                            ReceivedAt = new DateTime(2024, 5, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            ReferringGPId = "33333333-3333-3333-3333-333333333333",
                            SlaBreach = false,
                            SlaDeadline = new DateTime(2024, 5, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            SlaPaused = false,
                            SpecialistType = "Cardiology",
                            Status = 1,
                            Urgency = 3
                        },
                        new
                        {
                            Id = new Guid("5f0c804b-a557-4a84-ba06-592ee2aea1d2"),
                            AssignedToUserId = new Guid("33333333-3333-3333-3333-333333333333"),
                            CaseNo = "Ref-000002",
                            CreatedAt = new DateTime(2024, 5, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedByUserId = new Guid("33333333-3333-3333-3333-333333333333"),
                            PatientId = new Guid("66666666-6666-6666-6666-666655555555"),
                            PriorityScore = 30.199999999999999,
                            Reason = "Knee pain",
                            ReceivedAt = new DateTime(2024, 5, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            ReferringGPId = "33333333-3333-3333-3333-333333333333",
                            SlaBreach = false,
                            SlaDeadline = new DateTime(2024, 6, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            SlaPaused = false,
                            SpecialistType = "Orthopedics",
                            Status = 2,
                            Urgency = 1
                        },
                        new
                        {
                            Id = new Guid("a6012e7b-ee72-4523-89be-1b9f0992535f"),
                            AssignedToUserId = new Guid("44444444-4444-4444-4444-444444444444"),
                            CaseNo = "Ref-000003",
                            CreatedAt = new DateTime(2024, 5, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedByUserId = new Guid("44444444-4444-4444-4444-444444444444"),
                            PatientId = new Guid("77777777-7777-7777-7777-777755555555"),
                            PriorityScore = 55.0,
                            Reason = "Recurring headaches",
                            ReceivedAt = new DateTime(2024, 5, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            ReferringGPId = "44444444-4444-4444-4444-444444444444",
                            SlaBreach = false,
                            SlaDeadline = new DateTime(2024, 6, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            SlaPaused = false,
                            SpecialistType = "Neurology",
                            Status = 3,
                            Urgency = 2
                        },
                        new
                        {
                            Id = new Guid("78064ad5-a6b0-44f7-a2c8-1955878ea687"),
                            AssignedToUserId = new Guid("44444444-4444-4444-4444-444444444444"),
                            CaseNo = "Ref-000004",
                            CreatedAt = new DateTime(2024, 5, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedByUserId = new Guid("44444444-4444-4444-4444-444444444444"),
                            PatientId = new Guid("88888888-8888-8888-8888-888855555555"),
                            PriorityScore = 22.800000000000001,
                            Reason = "Skin rash",
                            ReceivedAt = new DateTime(2024, 5, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            ReferringGPId = "44444444-4444-4444-4444-444444444444",
                            SlaBreach = false,
                            SlaDeadline = new DateTime(2024, 6, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            SlaPaused = false,
                            SpecialistType = "Dermatology",
                            Status = 5,
                            Urgency = 1
                        },
                        new
                        {
                            Id = new Guid("cec98b32-5119-4ffd-9ab4-de02d98f81ae"),
                            AssignedToUserId = new Guid("33333333-3333-3333-3333-333333333333"),
                            CaseNo = "Ref-000005",
                            CreatedAt = new DateTime(2024, 5, 31, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedByUserId = new Guid("33333333-3333-3333-3333-333333333333"),
                            PatientId = new Guid("99999999-9999-9999-9999-999955555555"),
                            PriorityScore = 98.5,
                            Reason = "Mass detection",
                            ReceivedAt = new DateTime(2024, 5, 31, 0, 0, 0, 0, DateTimeKind.Local),
                            ReferringGPId = "33333333-3333-3333-3333-333333333333",
                            SlaBreach = false,
                            SlaDeadline = new DateTime(2024, 5, 31, 4, 0, 0, 0, DateTimeKind.Local),
                            SlaPaused = false,
                            SpecialistType = "Oncology",
                            Status = 1,
                            Urgency = 3
                        },
                        new
                        {
                            Id = new Guid("eea83374-f069-4313-bbef-607a41558118"),
                            AssignedToUserId = new Guid("44444444-4444-4444-4444-444444444444"),
                            CaseNo = "Ref-000006",
                            CreatedAt = new DateTime(2024, 5, 30, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedByUserId = new Guid("44444444-4444-4444-4444-444444444444"),
                            PatientId = new Guid("aaaaaaaa-5555-5555-5555-555555555555"),
                            PriorityScore = 48.299999999999997,
                            Reason = "Stomach issues",
                            ReceivedAt = new DateTime(2024, 5, 30, 0, 0, 0, 0, DateTimeKind.Local),
                            ReferringGPId = "44444444-4444-4444-4444-444444444444",
                            SlaBreach = false,
                            SlaDeadline = new DateTime(2024, 6, 6, 0, 0, 0, 0, DateTimeKind.Local),
                            SlaPaused = false,
                            SpecialistType = "Gastroenterology",
                            Status = 1,
                            Urgency = 2
                        },
                        new
                        {
                            Id = new Guid("8da1adc8-e9cf-42ae-af04-0c0d698b9249"),
                            AssignedToUserId = new Guid("33333333-3333-3333-3333-333333333333"),
                            CaseNo = "Ref-000007",
                            CreatedAt = new DateTime(2024, 5, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedByUserId = new Guid("33333333-3333-3333-3333-333333333333"),
                            PatientId = new Guid("bbbbbbbb-5555-5555-5555-555555555555"),
                            PriorityScore = 66.099999999999994,
                            Reason = "Vision deterioration",
                            ReceivedAt = new DateTime(2024, 5, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            ReferringGPId = "33333333-3333-3333-3333-333333333333",
                            SlaBreach = false,
                            SlaDeadline = new DateTime(2024, 5, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            SlaPaused = false,
                            SpecialistType = "Ophthalmology",
                            Status = 4,
                            Urgency = 3
                        },
                        new
                        {
                            Id = new Guid("58e145b3-e68a-4e3b-9ad4-80b3c2eb6d32"),
                            AssignedToUserId = new Guid("44444444-4444-4444-4444-444444444444"),
                            CaseNo = "Ref-000008",
                            CreatedAt = new DateTime(2024, 5, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedByUserId = new Guid("44444444-4444-4444-4444-444444444444"),
                            PatientId = new Guid("cccccccc-5555-5555-5555-555555555555"),
                            PriorityScore = 41.700000000000003,
                            Reason = "Chronic cough",
                            ReceivedAt = new DateTime(2024, 5, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            ReferringGPId = "44444444-4444-4444-4444-444444444444",
                            SlaBreach = false,
                            SlaDeadline = new DateTime(2024, 5, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            SlaPaused = false,
                            SpecialistType = "Pulmonology",
                            Status = 6,
                            Urgency = 2
                        });
                });

            modelBuilder.Entity("ReferWell.Domain.Entities.ReferralAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ReferralId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ReferralId");

                    b.ToTable("tblReferralAttachment", (string)null);
                });

            modelBuilder.Entity("ReferWell.Domain.Entities.RoleMenuAccess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("HasAccess")
                        .HasColumnType("bit");

                    b.Property<string>("MenuItem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("tblRoleMenuAccess", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-000000000001"),
                            HasAccess = true,
                            MenuItem = "Dashboard",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-000000000002"),
                            HasAccess = true,
                            MenuItem = "Priority Config",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-000000000003"),
                            HasAccess = true,
                            MenuItem = "Mass Communications",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-000000000004"),
                            HasAccess = true,
                            MenuItem = "User Management",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-000000000005"),
                            HasAccess = true,
                            MenuItem = "Menu Access",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-000000000006"),
                            HasAccess = true,
                            MenuItem = "Dashboard",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-000000000007"),
                            HasAccess = true,
                            MenuItem = "Priority Config",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-000000000008"),
                            HasAccess = true,
                            MenuItem = "Mass Communications",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-000000000009"),
                            HasAccess = false,
                            MenuItem = "User Management",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-000000000010"),
                            HasAccess = false,
                            MenuItem = "Menu Access",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-000000000011"),
                            HasAccess = true,
                            MenuItem = "Dashboard",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-000000000012"),
                            HasAccess = false,
                            MenuItem = "Priority Config",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-000000000013"),
                            HasAccess = false,
                            MenuItem = "Mass Communications",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-000000000014"),
                            HasAccess = false,
                            MenuItem = "User Management",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-000000000015"),
                            HasAccess = false,
                            MenuItem = "Menu Access",
                            Role = 3
                        });
                });

            modelBuilder.Entity("ReferWell.Domain.Entities.SystemConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("SystemConfigs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Description = "Weight % for urgency in priority score",
                            Key = "weight_urgency",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Value = "50"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Description = "Weight % for wait time in priority score",
                            Key = "weight_waittime",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Value = "30"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Description = "Weight % for patient age in priority score",
                            Key = "weight_patient",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Value = "20"
                        });
                });

            modelBuilder.Entity("ReferWell.Domain.Entities.ApplicationUserRole", b =>
                {
                    b.HasOne("ReferWell.Domain.Entities.ApplicationUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReferWell.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("ReferWell.Domain.Entities.ApplicationUser", "PerformedByUser")
                        .WithMany("AuditLogs")
                        .HasForeignKey("PerformedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReferWell.Domain.Entities.Referral", "Referral")
                        .WithMany("AuditLogs")
                        .HasForeignKey("ReferralId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PerformedByUser");

                    b.Navigation("Referral");
                });

            modelBuilder.Entity("ReferWell.Domain.Entities.MassCommCampaign", b =>
                {
                    b.HasOne("ReferWell.Domain.Entities.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("ReferWell.Domain.Entities.MassCommMessage", b =>
                {
                    b.HasOne("ReferWell.Domain.Entities.MassCommCampaign", "Campaign")
                        .WithMany("Messages")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("ReferWell.Domain.Entities.Referral", b =>
                {
                    b.HasOne("ReferWell.Domain.Entities.ApplicationUser", "AssignedToUser")
                        .WithMany()
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ReferWell.Domain.Entities.ApplicationUser", "ClaimedByUser")
                        .WithMany()
                        .HasForeignKey("ClaimedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ReferWell.Domain.Entities.ApplicationUser", "CreatedByUser")
                        .WithMany("CreatedReferrals")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReferWell.Domain.Entities.Patient", "Patient")
                        .WithMany("Referrals")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedToUser");

                    b.Navigation("ClaimedByUser");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("ReferWell.Domain.Entities.ReferralAttachment", b =>
                {
                    b.HasOne("ReferWell.Domain.Entities.Referral", "Referral")
                        .WithMany("Attachments")
                        .HasForeignKey("ReferralId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Referral");
                });

            modelBuilder.Entity("ReferWell.Domain.Entities.ApplicationUser", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("CreatedReferrals");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("ReferWell.Domain.Entities.MassCommCampaign", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("ReferWell.Domain.Entities.Patient", b =>
                {
                    b.Navigation("Referrals");
                });

            modelBuilder.Entity("ReferWell.Domain.Entities.Referral", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("AuditLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
