// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReferWell.Infrastructure.Data;

#nullable disable

namespace ReferWell.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ReferWell.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@referwell.com",
                            FullName = "System Admin",
                            IsActive = true,
                            PasswordHash = "$2a$11$XEiDr9QOoCLcTH9lyxsiK.xAA7U.bXZxAkUZmt01W5PzvnL3IVNDa",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "nurse@referwell.com",
                            FullName = "Nurse Sarah",
                            IsActive = true,
                            PasswordHash = "$2a$11$lCaB5GQ49O7zEiUoDSF0JOFH8Ouq/TSyPTIPXV52plIIyfOmYkjgy",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "gp1@referwell.com",
                            FullName = "Dr. James Wilson",
                            IsActive = true,
                            PasswordHash = "$2a$11$KLbW14SVatQ25b62lvogieQ3BTUaUJxzEQX8ij/etiuA/BrsuVucS",
                            Role = 3
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "gp2@referwell.com",
                            FullName = "Dr. Amelia Hart",
                            IsActive = true,
                            PasswordHash = "$2a$11$c462mFKpwQIu4TPmtMfQy.B8S.EDx/ByKBKO.AH7GYe8xVauoGJiy",
                            Role = 3
                        });
                });

            modelBuilder.Entity("ReferWell.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FromStatus")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PerformedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReferralId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ToStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PerformedByUserId");

                    b.HasIndex("ReferralId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("ReferWell.Domain.Entities.MassCommCampaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BodyTemplate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FilterCriteria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubjectTemplate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("MassCommCampaigns");
                });

            modelBuilder.Entity("ReferWell.Domain.Entities.MassCommMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecipientEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RenderedBody")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.ToTable("MassCommMessages");
                });

            modelBuilder.Entity("ReferWell.Domain.Entities.Referral", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ClaimedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ClaimedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PatientDateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double>("PriorityScore")
                        .HasColumnType("float");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReferringGPId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<bool>("SlaBreach")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SlaDeadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("SpecialistType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Urgency")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClaimedByUserId");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("Referrals");

                    b.HasData(
                        new
                        {
                            Id = new Guid("46e92d71-fe4e-45cb-9781-cae95b336c3d"),
                            CreatedAt = new DateTime(2024, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("33333333-3333-3333-3333-333333333333"),
                            PatientDateOfBirth = new DateTime(1955, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            PatientName = "Alice Martin",
                            PriorityScore = 75.5,
                            Reason = "Chest pain",
                            ReceivedAt = new DateTime(2024, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReferringGPId = "33333333-3333-3333-3333-333333333333",
                            SlaBreach = false,
                            SlaDeadline = new DateTime(2024, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            SpecialistType = "Cardiology",
                            Status = 1,
                            Urgency = 3
                        },
                        new
                        {
                            Id = new Guid("b8524c28-a6cf-4683-8dee-a706e9da82ce"),
                            CreatedAt = new DateTime(2024, 5, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("33333333-3333-3333-3333-333333333333"),
                            PatientDateOfBirth = new DateTime(1970, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            PatientName = "Bob Clarke",
                            PriorityScore = 30.199999999999999,
                            Reason = "Knee pain",
                            ReceivedAt = new DateTime(2024, 5, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReferringGPId = "33333333-3333-3333-3333-333333333333",
                            SlaBreach = false,
                            SlaDeadline = new DateTime(2024, 6, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            SpecialistType = "Orthopedics",
                            Status = 2,
                            Urgency = 1
                        },
                        new
                        {
                            Id = new Guid("5da6a25f-9982-45b9-9501-d4a3ae7ca24d"),
                            CreatedAt = new DateTime(2024, 5, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("44444444-4444-4444-4444-444444444444"),
                            PatientDateOfBirth = new DateTime(1940, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            PatientName = "Carol Ahmed",
                            PriorityScore = 55.0,
                            Reason = "Recurring headaches",
                            ReceivedAt = new DateTime(2024, 5, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReferringGPId = "44444444-4444-4444-4444-444444444444",
                            SlaBreach = false,
                            SlaDeadline = new DateTime(2024, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            SpecialistType = "Neurology",
                            Status = 3,
                            Urgency = 2
                        },
                        new
                        {
                            Id = new Guid("b52ae6f9-4118-4009-9627-7b1107b8f1e1"),
                            CreatedAt = new DateTime(2024, 5, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("44444444-4444-4444-4444-444444444444"),
                            PatientDateOfBirth = new DateTime(1985, 2, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            PatientName = "David Johnson",
                            PriorityScore = 22.800000000000001,
                            Reason = "Skin rash",
                            ReceivedAt = new DateTime(2024, 5, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReferringGPId = "44444444-4444-4444-4444-444444444444",
                            SlaBreach = false,
                            SlaDeadline = new DateTime(2024, 6, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            SpecialistType = "Dermatology",
                            Status = 5,
                            Urgency = 1
                        },
                        new
                        {
                            Id = new Guid("ffa5b158-cd92-45f0-b2e8-0e6a22c87dac"),
                            CreatedAt = new DateTime(2024, 5, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("33333333-3333-3333-3333-333333333333"),
                            PatientDateOfBirth = new DateTime(1932, 8, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            PatientName = "Eva Rodriguez",
                            PriorityScore = 98.5,
                            Reason = "Mass detection",
                            ReceivedAt = new DateTime(2024, 5, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReferringGPId = "33333333-3333-3333-3333-333333333333",
                            SlaBreach = false,
                            SlaDeadline = new DateTime(2024, 5, 31, 4, 0, 0, 0, DateTimeKind.Utc),
                            SpecialistType = "Oncology",
                            Status = 1,
                            Urgency = 4
                        },
                        new
                        {
                            Id = new Guid("99b45e6b-3193-4d33-b80b-3feb2b7d609a"),
                            CreatedAt = new DateTime(2024, 5, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("44444444-4444-4444-4444-444444444444"),
                            PatientDateOfBirth = new DateTime(1960, 4, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            PatientName = "Frank Lee",
                            PriorityScore = 48.299999999999997,
                            Reason = "Stomach issues",
                            ReceivedAt = new DateTime(2024, 5, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReferringGPId = "44444444-4444-4444-4444-444444444444",
                            SlaBreach = false,
                            SlaDeadline = new DateTime(2024, 6, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            SpecialistType = "Gastroenterology",
                            Status = 1,
                            Urgency = 2
                        },
                        new
                        {
                            Id = new Guid("30fdba99-25df-4e70-9353-0805e3c51ad2"),
                            CreatedAt = new DateTime(2024, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("33333333-3333-3333-3333-333333333333"),
                            PatientDateOfBirth = new DateTime(1978, 12, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            PatientName = "Grace Kim",
                            PriorityScore = 66.099999999999994,
                            Reason = "Vision deterioration",
                            ReceivedAt = new DateTime(2024, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReferringGPId = "33333333-3333-3333-3333-333333333333",
                            SlaBreach = false,
                            SlaDeadline = new DateTime(2024, 5, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            SpecialistType = "Ophthalmology",
                            Status = 4,
                            Urgency = 3
                        },
                        new
                        {
                            Id = new Guid("2f7d3d63-4b9e-454c-bbec-ff5ffea09033"),
                            CreatedAt = new DateTime(2024, 5, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = new Guid("44444444-4444-4444-4444-444444444444"),
                            PatientDateOfBirth = new DateTime(1945, 6, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            PatientName = "Henry Smith",
                            PriorityScore = 41.700000000000003,
                            Reason = "Chronic cough",
                            ReceivedAt = new DateTime(2024, 5, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReferringGPId = "44444444-4444-4444-4444-444444444444",
                            SlaBreach = false,
                            SlaDeadline = new DateTime(2024, 5, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            SpecialistType = "Pulmonology",
                            Status = 6,
                            Urgency = 2
                        });
                });

            modelBuilder.Entity("ReferWell.Domain.Entities.SystemConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("SystemConfigs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Description = "Weight % for urgency in priority score",
                            Key = "weight_urgency",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "50"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Description = "Weight % for wait time in priority score",
                            Key = "weight_waittime",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "30"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Description = "Weight % for patient age in priority score",
                            Key = "weight_patient",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "20"
                        });
                });

            modelBuilder.Entity("ReferWell.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("ReferWell.Domain.Entities.ApplicationUser", "PerformedByUser")
                        .WithMany("AuditLogs")
                        .HasForeignKey("PerformedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReferWell.Domain.Entities.Referral", "Referral")
                        .WithMany("AuditLogs")
                        .HasForeignKey("ReferralId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PerformedByUser");

                    b.Navigation("Referral");
                });

            modelBuilder.Entity("ReferWell.Domain.Entities.MassCommCampaign", b =>
                {
                    b.HasOne("ReferWell.Domain.Entities.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("ReferWell.Domain.Entities.MassCommMessage", b =>
                {
                    b.HasOne("ReferWell.Domain.Entities.MassCommCampaign", "Campaign")
                        .WithMany("Messages")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("ReferWell.Domain.Entities.Referral", b =>
                {
                    b.HasOne("ReferWell.Domain.Entities.ApplicationUser", "ClaimedByUser")
                        .WithMany()
                        .HasForeignKey("ClaimedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ReferWell.Domain.Entities.ApplicationUser", "CreatedByUser")
                        .WithMany("CreatedReferrals")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClaimedByUser");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("ReferWell.Domain.Entities.ApplicationUser", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("CreatedReferrals");
                });

            modelBuilder.Entity("ReferWell.Domain.Entities.MassCommCampaign", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("ReferWell.Domain.Entities.Referral", b =>
                {
                    b.Navigation("AuditLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
